# Generated by Django 5.2.3 on 2025-07-05 15:53

import django.contrib.postgres.indexes
import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product_category',
                'managed': True,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='trgm_category_name_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.productcategory')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated')),
                ('image', utils.fields.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=80, scale=None, size=[1024, 768], upload_to='images', verbose_name='Product image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Is image main?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='examples.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'slug'], name='trgm_product_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
