# Generated by Django 5.2.3 on 2025-06-23 16:03

import django.contrib.postgres.indexes
import django.db.models.deletion
import utils.fields
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'product_category',
                'managed': True,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='trgm_category_name_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', utils.fields.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=False, null=True, quality=80, scale=None, size=[1024, 768], upload_to='images', verbose_name='Изображение')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='_test.productcategory')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name', 'slug'], name='trgm_product_search_idx', opclasses=['gin_trgm_ops', 'gin_trgm_ops'])],
            },
        ),
    ]
